apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-2048
  template:
    metadata:
      labels:
        app: game-2048
    spec:
      containers:
        - name: game-2048-container
          image: ghcr.io/pranavg2104/2048:latest
          ports:
            - containerPort: 8080
